fixtures:
  forge_modules:
    stdlib:
      repo: "puppetlabs/stdlib"
    vcsrepo:
      repo: "puppetlabs/vcsrepo"
  repositories:
    wget: "https://github.com/maestrodev/puppet-wget.git"
  symlinks:
    ohmyzsh: "#{source_dir}"
